Repository StrHat/Backend, pull requests merged in 2025-05, with the labels that each got.

#38 [REFACTOR] 일기 API 코드리뷰 반영
  src/main/java/com/konkuk/strhat/ai/prompt/diary_feedback/DiaryFeedbackPrompt.java
  src/main/java/com/konkuk/strhat/ai/web_client/GptClient.java
  src/main/java/com/konkuk/strhat/domain/diary/application/DiaryService.java
Labels: 👩🏻‍💻은정, refactor

#39 [REFACTOR] DTO 관련 코드 컨벤션 적용
  src/main/java/com/konkuk/strhat/ai/prompt/diary_feedback/DiaryFeedbackRequestDto.java
  src/main/java/com/konkuk/strhat/domain/diary/application/DiaryService.java
  src/main/java/com/konkuk/strhat/domain/diary/application/FeedbackService.java
  src/main/java/com/konkuk/strhat/domain/diary/dto/CheckDiaryResponse.java
  src/main/java/com/konkuk/strhat/domain/diary/dto/DiaryContentResponse.java
  src/main/java/com/konkuk/strhat/domain/diary/dto/DiarySaveRequest.java
  src/main/java/com/konkuk/strhat/domain/diary/dto/DiarySaveResponse.java
  src/main/java/com/konkuk/strhat/domain/diary/dto/FeedbackResponse.java
  src/main/java/com/konkuk/strhat/domain/user/application/JwtProvider.java
  src/main/java/com/konkuk/strhat/domain/user/application/KakaoOAuthService.java
  src/main/java/com/konkuk/strhat/domain/user/application/UserService.java
  src/main/java/com/konkuk/strhat/domain/user/dao/UserRepository.java
  src/main/java/com/konkuk/strhat/domain/user/dto/GetUserInfoResponse.java
  src/main/java/com/konkuk/strhat/domain/user/dto/PostKakaoSignInRequest.java
  src/main/java/com/konkuk/strhat/domain/user/dto/PostKakaoSignInResponse.java
  src/main/java/com/konkuk/strhat/domain/user/dto/PostSignUpRequest.java
  src/main/java/com/konkuk/strhat/domain/user/dto/TokenDto.java
  src/main/java/com/konkuk/strhat/domain/user/dto/UserInfoDto.java
Labels: 👩🏻‍💻은정, refactor

#45 [FEAT] 챗봇 대화 기능 API 구현
  src/main/java/com/konkuk/strhat/ai/prompt/chat/ChatPrompt.java
  src/main/java/com/konkuk/strhat/ai/prompt/chat/ChatRequestDto.java
  src/main/java/com/konkuk/strhat/ai/prompt/chat/ChatResponseDto.java
  src/main/java/com/konkuk/strhat/ai/prompt/stress_score/DailyStressScorePrompt.java
  src/main/java/com/konkuk/strhat/ai/prompt/stress_score/WeeklyStressSummaryPrompt.java
  src/main/java/com/konkuk/strhat/domain/chat/api/ChatController.java
  src/main/java/com/konkuk/strhat/domain/chat/application/AIChatService.java
  src/main/java/com/konkuk/strhat/domain/chat/application/ChatService.java
  src/main/java/com/konkuk/strhat/domain/chat/dao/ChatMessageRepository.java
  src/main/java/com/konkuk/strhat/domain/chat/dto/ChatMessageLogResponse.java
  src/main/java/com/konkuk/strhat/domain/chat/dto/ChatMessageResponse.java
  src/main/java/com/konkuk/strhat/domain/chat/dto/ChatRequest.java
  src/main/java/com/konkuk/strhat/domain/chat/dto/ChatResponse.java
  src/main/java/com/konkuk/strhat/domain/chat/entity/ChatMessage.java
  src/main/java/com/konkuk/strhat/domain/chat/enums/ChatMode.java
  src/main/java/com/konkuk/strhat/domain/chat/exception/InvalidChatResultException.java
  src/main/java/com/konkuk/strhat/domain/diary/application/DiaryService.java
  src/main/java/com/konkuk/strhat/domain/diary/dto/CheckDiaryResponse.java
  src/main/java/com/konkuk/strhat/domain/diary/dto/DiaryContentResponse.java
  src/main/java/com/konkuk/strhat/domain/diary/dto/DiarySaveResponse.java
  src/main/java/com/konkuk/strhat/domain/diary/dto/FeedbackResponse.java
  src/main/java/com/konkuk/strhat/global/error/ErrorCode.java
Labels: feature, 👩🏻‍💻은정

#47 [FIX] PSS, SRI 기준 점수 수정
  src/main/java/com/konkuk/strhat/domain/selfDiagnosis/application/SelfDiagnosisService.java
Labels: bug fix, 🧑🏻‍💻유혁

#50 [FIX] OAuth 방식 변경
  src/main/java/com/konkuk/strhat/domain/user/api/OauthController.java
  src/main/java/com/konkuk/strhat/domain/user/api/UserController.java
  src/main/java/com/konkuk/strhat/domain/user/application/CustomUserDetailsService.java
  src/main/java/com/konkuk/strhat/domain/user/application/JwtProvider.java
  src/main/java/com/konkuk/strhat/domain/user/application/KakaoOAuthService.java
  src/main/java/com/konkuk/strhat/domain/user/application/UserService.java
  src/main/java/com/konkuk/strhat/domain/user/dao/RefreshTokenRepository.java
  src/main/java/com/konkuk/strhat/domain/user/dao/UserRepository.java
  src/main/java/com/konkuk/strhat/domain/user/dto/PostKakaoSignInResponse.java
  src/main/java/com/konkuk/strhat/domain/user/dto/PostSignUpRequest.java
  src/main/java/com/konkuk/strhat/domain/user/entity/CustomUserDetails.java
  src/main/java/com/konkuk/strhat/domain/user/entity/RefreshToken.java
  src/main/java/com/konkuk/strhat/domain/user/entity/User.java
  src/main/java/com/konkuk/strhat/domain/user/exception/DuplicateKakaoIdException.java
  src/main/java/com/konkuk/strhat/global/config/SecurityConfig.java
  src/main/java/com/konkuk/strhat/global/error/ErrorCode.java
  src/main/java/com/konkuk/strhat/global/filter/JwtAuthenticationFilter.java
  src/main/java/com/konkuk/strhat/global/util/SecurityUtil.java
Labels: bug fix, 🧑🏻‍💻유혁

#52 [FEAT] 홈 API 구현
  src/main/java/com/konkuk/strhat/domain/stressScore/dao/StressScoreRepository.java
  src/main/java/com/konkuk/strhat/domain/user/api/HomeController.java
  src/main/java/com/konkuk/strhat/domain/user/application/HomeService.java
  src/main/java/com/konkuk/strhat/domain/user/application/UserService.java
  src/main/java/com/konkuk/strhat/domain/user/dto/GetHomeResponse.java
  src/main/java/com/konkuk/strhat/domain/user/dto/PostSignUpRequest.java
  src/main/java/com/konkuk/strhat/domain/user/enums/Gender.java
  src/main/java/com/konkuk/strhat/domain/user/enums/Job.java
Labels: feature, 🧑🏻‍💻유혁

#56 [FIX] 로그아웃 API 오류 수정
  src/main/java/com/konkuk/strhat/domain/user/application/UserService.java
  src/main/java/com/konkuk/strhat/domain/user/dao/RefreshTokenRepository.java
Labels: bug fix, 🧑🏻‍💻유혁

#57 [FIX] 홈 API 오류 수정
  src/main/java/com/konkuk/strhat/domain/user/api/HomeController.java
Labels: bug fix, 🧑🏻‍💻유혁

#58 [DEPLOY] 홈 API 및 로그아웃 API 오류 해결 후 배포
  src/main/java/com/konkuk/strhat/domain/user/api/HomeController.java
  src/main/java/com/konkuk/strhat/domain/user/application/UserService.java
  src/main/java/com/konkuk/strhat/domain/user/dao/RefreshTokenRepository.java
Labels: deploy
